# @format

version: '3.8'

services:
  # Spring Boot Application
  posbackend:
    image: gitlab.oneshell.in:5050/server/posbackend/qa:latest
    container_name: posbackend
    restart: always
    ports:
      - '8062:8062'
    depends_on:
      - mongodb
      - nats-server
    environment:
      - NATS_URL=nats://nats-server:4222
      - SPRING_PROFILES_ACTIVE=default
      - MONGODB_URI=mongodb://mongodb:27017/pos
    deploy:
      resources:
        limits:
          cpus: '1.0' # Limit to 1 CPU core
          memory: 1536M # Limit to 1.5GB RAM
        reservations:
          cpus: '0.3' # Reserve 0.5 CPU cores
          memory: 350M # Reserve 512MB RAM
    networks:
      - app-network

  # MongoDB
  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: always
    volumes:
      - ~/data:/data/db
    labels:
      - 'com.centurylinklabs.watchtower.enable=false'
    ports:
      - '27017:27017'
    deploy:
      resources:
        limits:
          cpus: '1.0' # Limit to 1 CPU core
          memory: 1536M # Limit to 1.5GB RAM
        reservations:
          cpus: '0.3' # Reserve 0.5 CPU cores
          memory: 300M # Reserve 512MB RAM
    networks:
      - app-network

  # NATS Server
  nats-server:
    image: nats:latest
    container_name: nats-server
    restart: always
    labels:
      - 'com.centurylinklabs.watchtower.enable=false'
    ports:
      - '4222:4222'
      - '8222:8222'
      - '8080:8080'
    volumes:
      - ./nats-server.conf:/nats-server.conf
    command: ['--config', '/nats-server.conf']
    deploy:
      resources:
        limits:
          cpus: '0.75' # Limit to 0.75 CPU cores
          memory: 1024M # Limit to 1GB RAM
        reservations:
          cpus: '0.2' # Reserve 0.5 CPU cores
          memory: 64M # Reserve 512MB RAM
    networks:
      - app-network

  # Watchtower
  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    restart: unless-stopped
    labels:
      - 'com.centurylinklabs.watchtower.enable=false'
    environment:
      - TZ=Europe/London
      - WATCHTOWER_CLEANUP=true
      - WATCHTOWER_ROLLING_RESTART=true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ~/.docker/config.json:/config.json # Mount Docker auth file
    command: --interval 20
    deploy:
      resources:
        limits:
          cpus: '0.2' # Limit to 0.5 CPU cores
          memory: 128M # Limit to 128MB RAM
        reservations:
          cpus: '0.1' # Reserve 0.25 CPU cores
          memory: 64M # Reserve 64MB RAM
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
