# @format

version: '3.8'

services:
  # Spring Boot Application
  posbackend:
    image: gitlab.oneshell.in:5050/server/posbackend/qa:latest
    container_name: posbackend
    restart: always
    depends_on:
      - mongodb
      - nats-server
    environment:
      - NATS_URL=nats://nats-server:4222
      - SPRING_PROFILES_ACTIVE=default
      - MONGODB_URI=mongodb://mongodb:27017/pos
    networks:
      - app-network

  # MongoDB
  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: always
    volumes:
      - ~/data:/data/db
    labels:
      - 'com.centurylinklabs.watchtower.enable=false'
    ports:
      - '27017:27017'
    networks:
      - app-network

  # NATS Server
  nats-server:
    image: nats:latest
    container_name: nats-server
    restart: always
    labels:
      - 'com.centurylinklabs.watchtower.enable=false'
    ports:
      - '4222:4222'
      - '8222:8222'
      - '8080:8080'
    volumes:
      - ./nats-server.conf:/nats-server.conf
    command: ['--config', '/nats-server.conf']
    networks:
      - app-network

  # Watchtower
  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    restart: unless-stopped
    labels:
      - 'com.centurylinklabs.watchtower.enable=false'
    environment:
      - TZ=Europe/London
      - WATCHTOWER_CLEANUP=true
      - WATCHTOWER_ROLLING_RESTART=true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ~/.docker/config.json:/config.json # Mount Docker auth file
    command: --interval 20
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
